---
builds:
  -
    flags: -tags "static_build"
    ldflags: -w -X github.com/prologic/tube/.Version={{.Version}} -X github.com/prologic/tube/.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - freebsd
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
brews:
  -
    github:
      owner: prologic
      name: homebrew-tap
    homepage: "https://github.io/prologic/tube"
    description: |
      tube is a Youtube-like (without censorship and features you don't need!)
      Video Sharing App written in Go which also supports automatic
      transcoding to MP4 H.265 AAC, multiple collections and RSS feed.
    dependencies:
      - ffmpeg
signs:
  artifacts: checksum
archives:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
